services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      FLASK_DEBUG: 0
      FLASK_ENV: "production"
      CACHE_DIR: "/data/cache"
      OUTPUT_DIR: "/data/output"
      UPLOAD_DIR: "/data/upload"
    env_file:
      - ./.env
